name: main

on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

jobs:
  rclgo:
    runs-on: ubuntu-latest
    container: ros:galactic-ros-core
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go environment
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install additional tools and libraries
        run: |
          apt-get update
          apt-get install -y \
            gcc \
            make \
            ros-galactic-builtin-interfaces \
            ros-galactic-example-interfaces \
            ros-galactic-sensor-msgs \
            ros-galactic-std-msgs \
            ros-galactic-std-srvs \
            ros-galactic-test-msgs

      - name: Run tests
        run: |
          . /opt/ros/galactic/setup.sh
          make test
